services:
  kilik.translation.services.load_translation_service:
    arguments: ['%kernel.root_dir%','%translator.default_path%']
    class: Kilik\TranslationBundle\Services\LoadTranslationService

imports:
  - { resource: commands.yml }
